"""Analysis of calibration images for a camera with a polynomial correction model.

A small part of this code has been AI generated by ChatGPT in April 2025.
The script checks for checkerboard patterns of the given size (change line 18) in all images in `config/calibration_images/*.png`. The configuration results gets saved as `config/distortion_correction.json` and an example transformed image gets stored to `config/calibrated_images/calibresult.png`.


"""

import cv2
import numpy as np
import os
import glob
import json 

# A large portion of this code has been AI generated by ChatGPT in April 2025. (I wrote this before making mayor changes lol, now its only minor)

# Defining the dimensions of checkerboard
CHECKERBOARD = (15-1,21-1) # must be the exact number of corners (number of rows/cols -1)
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)
 
# Creating vector to store vectors of 3D points for each checkerboard image
objpoints = []
# Creating vector to store vectors of 2D points for each checkerboard image
imgpoints = [] 
 
 
# Defining the world coordinates for 3D points
objp = np.zeros((1, CHECKERBOARD[0] * CHECKERBOARD[1], 3), np.float32)
objp[0,:,:2] = np.mgrid[0:CHECKERBOARD[0], 0:CHECKERBOARD[1]].T.reshape(-1, 2)
prev_img_shape = None

# Extracting path of individual image stored in a given directory
images = glob.glob('config/calibration_images/*.png')
print(images)
for fname in images:
    img = cv2.imread(fname)
    #print(img)
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    # Find the chess board corners
    # If desired number of corners are found in the image then ret = true
    ret, corners = cv2.findChessboardCorners(gray, CHECKERBOARD, cv2.CALIB_CB_ADAPTIVE_THRESH + cv2.CALIB_CB_FAST_CHECK + cv2.CALIB_CB_NORMALIZE_IMAGE)
    print(ret)
    """
    If desired number of corner are detected,
    we refine the pixel coordinates and display 
    them on the images of checker board
    """
    if ret == True:
        objpoints.append(objp)
        # refining pixel coordinates for given 2d points.
        corners2 = cv2.cornerSubPix(gray, corners, (11,11),(-1,-1), criteria)
         
        imgpoints.append(corners2)
 
        # Draw and display the corners
        img = cv2.drawChessboardCorners(img, CHECKERBOARD, corners2, ret)
     
        cv2.imwrite(f'config/calibrated_images/{fname[:-4]}-chess.png', img)
    #cv2.waitKey(0)
 
#cv2.destroyAllWindows()
 
h,w = img.shape[:2]
 
"""
Performing camera calibration by 
passing the value of known 3D points (objpoints)
and corresponding pixel coordinates of the 
detected corners (imgpoints)
"""
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)
 
print("Camera matrix (K in vpi.WarpMap.polynomial_correction): \n")
print(mtx)
print("dist (rcoeffs in the vpi.WarpMap.polynomial_correction, weak documentation) : \n")
print(dist)
print("rvecs (unused): \n")
print(rvecs)
print("tvecs (unused): \n")
print(tvecs)

img = cv2.imread(images[0])
h,  w = img.shape[:2]
newcameramtx, roi = cv2.getOptimalNewCameraMatrix(mtx, dist, (w,h), 1, (w,h))
# undistort
dst = cv2.undistort(img, mtx, dist, None, newcameramtx)

# crop the image
x, y, w, h = roi
dst = dst[y:y+h, x:x+w]
cv2.imwrite('config/calibrated_images/calibresult.png', dst)

#%% Write to config
config_file = "config/distortion_correction.json"
with open("config/distortion_correction.json", "w") as file:
    json.dump({"mtx": mtx.astype(float).tolist(), "dist": dist[0].astype(float).tolist(), "rvecs": rvecs[0].astype(float).tolist(), "tvecs": tvecs[0].astype(float).tolist()}, file, indent=4)
print("Written to", config_file)